### ISSUE TITLE
Tests inside let expressions are ignored

### ISSUE THREAD

**Issue by den1k** [hyperfiddle/rcf#26]
The tests inside the let expression do not work

```clojure
(tests
  (let [zoom-id "948217304"
        {:keys [body]} @(http/get
                          (str "<...>&zoom-id=" zoom-id))
        payload (u/read-json-keywordized body)]
    (tests
     (every? #{zoom-id} (mapv :zoom-id payload))) := true))
```

**Comment by dustingetz** [comment]
Thanks Dennis. the feature/async branch handles this gracefully, you can try it if you want (we're using it) but we aren't committed to the syntax yet. In the meantime I would refactor let to def and stick to top level assertions. We can revisit deep assertions after the async branch lands.

**Comment by dustingetz** [comment]
```(tests
  (let [a 1]
    (tests
      a := 1)))
✅=> nil
```

This works now btw

**Comment by den1k** [comment]
Sounds good. Closing since it sounds like this is already working and will likely be merged into master soon.
