### ISSUE TITLE
Disable emoji

### ISSUE THREAD

**Issue by NoahTheDuke** [hyperfiddle/rcf#29]
I'm loving the library, but I don't like having the emoji appear in my test reporting when running tests from the command line. Is this possible?

**Comment by ggeoffrey** [comment]
RCF uses `clojure.test` reporters. You can override them however you like. Defaults are in [reporters.clj](https://github.com/hyperfiddle/rcf/blob/master/src/hyperfiddle/rcf/reporters.clj) for clojure and  [reporters.cljs](https://github.com/hyperfiddle/rcf/blob/master/src/hyperfiddle/rcf/reporters.cljs) for clojurescript

**Comment by NoahTheDuke** [comment]
Oh perfect, I'll check that out.
