### ISSUE TITLE
cut a release

### ISSUE THREAD

**Issue by xificurC** [hyperfiddle/rcf#43]
I want to depend on this library and if I want to deploy my library to clojars I can't include rcf in the pom because maven doesn't support git packages like deps.edn does. Asking end users to include it by hand is pushing the burden onto the end user.

AFAIU rcf can't be included as a test dependency since the implementation code requires it into its namespace and uses at least the `tests` macro. So I have to include it as a runtime dependency whether the tests are run or not. For that reason I'd like to see a release, even marked as alpha, doesn't matter. Is that reasonable?

Thanks!

**Comment by dustingetz** [comment]
Will do, sorry about that, it's been on the todo list for a while

**Comment by dustingetz** [comment]
Does anyone have a recommended tools.build plugin for this? We may just write the pom.xml by hand

**Comment by NoahTheDuke** [comment]
@seancorfield's [build-clj](https://github.com/seancorfield/build-clj) looks really nice tho I haven't had a chance to use it yet.

**Comment by seancorfield** [comment]
Feel free to ask Qs about it -- and take a look at https://github.com/seancorfield/honeysql for an example of a clj/cljs project that automatically builds a JAR and releases it to Clojars when a release is cut on GitHub (via GitHub Actions -- it also pushes a SNAPSHOT release on every commit that passes the test suite).

**Comment by dustingetz** [comment]
The stable version of RCF is released: `com.hyperfiddle/rcf {:mvn/version "20220405"}`
Sean we're using your build-clj, thank you!
