### ISSUE TITLE
How to test something is equal to a non literal?

### ISSUE THREAD

**Issue by didibus** [hyperfiddle/rcf#45]
How would I test something like:

```
(ex-info "error" {}) := (ex-info "error" {})
```

It seems the right-hand side doesn't get evaluated.

**Comment by didibus** [comment]
Nevermind, I thought ex-info had value equality, but they don't, so `(= (ex-info "error" {}) (ex-info "error" {}))` is false.

I was able to do this instead:

```
(let [error (ex-info "error" {})]
    error := error)
```

**Comment by ggeoffrey** [comment]
Related to #36

Both left and right hand sides are evaluated, but rhs is reported symbolically. We need to improve the overall reporting.
