### ISSUE TITLE
Wildcard sensitive to ordering within maps

### ISSUE THREAD

**Issue by zeitstein** [hyperfiddle/rcf#48]
```clojure
(tests
  {:a :b :c :d} := {:a :b :c _} ;; works as expected
  {:a :b :c :d} := {:c _ :a :b} ;; doesn't
)
```

Side note: would be nice if `'_` was supported to not trigger linting errors. (Though `:= '{:a _}` works.)

**Comment by dustingetz** [comment]
Thank you for the report! Confirmed the issue in master. It's fixed in our internal dev branch so probably not worth your time to try to figure it out. FYI the dev branch is not released and has a few issues.

```
(tests
  {:a :b :c :d} := {:a :b :c _} ;; works as expected
  {:a :b :c :d} := {:c _ :a :b} ;; doesn't
  )
✅
❌ hyperfiddle.rcf.tests:69 
in {:a :b, :c :d}

{:a :b, :c :d}
:<>
{:c _, :a :b}

=> {:a :b, :c :d}
```
