### ISSUE TITLE
Maps are order sensitive when using wildcards 

### ISSUE THREAD

**Issue by slifin** [hyperfiddle/rcf#52]
```
(tests
  {:a "a" :b "b"} := {:b "b" :a "a"}
  {:a "a" :b "b"} := {:a "a" :b "b"}
  {:a "a" :b "b"} := {:b _ :a _}
  {:a "a" :b "b"} := {:a _ :b _})
```

```
❌
in {:a "a", :b "b"}

{:a "a", :b "b"}
:<>
{:b _, :a _}
```

I'm not sure if this is intended or not but this behavior can result in very brittle tests since maps are purely associative and order shouldn't be relied on by default

**Comment by dustingetz** [comment]
Thank you Adrian
Duplicate of https://github.com/hyperfiddle/rcf/issues/48
Fixed in internal dev branch, technical alpha coming soon
